version: '3.8'
services:
  web:
    container_name: web_server
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./html:/var/www/html/
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
  php:
    container_name: php_7
    image: php:7-fpm
    ports:
      - 9000:9000
    volumes:
      - ./html:/var/www/html/
